language: python
sudo: false

python:
  - "3.4"

# Install and use Miniconda to fix scipy error on `pip install`
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  - python setup.py install

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - make test

# after_success:
#   - coveralls

notifications:
    email: false
    slack: cmi-sid:rNk6Ci6CIlpVROZkkAyt7eSB