language: python
sudo: false

python:
  - "3.4"

install:
  - pip install --only-binary=numpy,scipy
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - make test

#
# after_success:
#   - coveralls

notifications:
    email: false
    slack: cmi-sid:rNk6Ci6CIlpVROZkkAyt7eSB